[project]
name = "hpc_submission_launcher"
version = "0.1.0"
description = "HPC Submission Launcher for Hydra."
readme = "README.md"
authors = [{ name = "Carel van Niekerk", email = "cvanniekerk@hhu.de" }]
requires-python = ">=3.12"
dependencies = []